<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table product-list">
    <caption>Produits</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <?php 
            foreach ($products as $product) 
            {
                echo '<tr class="' . htmlspecialchars($product['group_name']) . '">
                        <td><a href="#">' . htmlspecialchars($product['name']) . '</a></td>
                        <td><a href="#">' . htmlspecialchars($product['group_name']) . '</a></td>
                        <td><a href="#">' . htmlspecialchars($product['price']) . '€</a></td>
                     </tr>';
            }
        ?>
    </tbody>
</table>