<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>LL! Commandes groupées</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/base.css">
	<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css" media="all" />
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="https://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    
    
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.png" alt="LL!Commandes!!">Love Live ! Commandes groupées !!
        </a>
    </h1>
    <nav>
       <?php 
            if($_SESSION) {
                echo '<div id="connected">
                    <a href="' . $requestUrl . '/cart">Mes commandes</a>
                    <a href="' . $requestUrl . '/deconnectino">Deconnection</a>
                        <a href="' . $requestUrl . '/admin?admin=boxes">Admin Panel</a>
                </div>
                <p>Bonjour, ' . htmlspecialchars($_SESSION['firstname']) . ' !</p>';
            }
            else {
                echo '<div id="not_connected">
                    <a href="' . $requestUrl . '/inscription">Inscription</a>
                    <a href="' . $requestUrl . '/connection">Connection</a>
                </div>';
            }
        ?>
    </nav>
    
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <!-- Code HTML/PHP à écrire -->
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <!-- <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>-->
    <p>Réalisé avec <i class="fa fa-star"></i> par Yoan</p>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/cart.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/success.js"></script>
</body>
</html>